/** @type {import('tailwindcss').Config} */
// Design tokens pulled from the Stitch "NUHRS Health Portal" project.
//
// Colors are wired to CSS variables (RGB channel triplets) defined in index.css
// so a theme can be re-skinned by overriding the channels on a wrapper element
// — the patient portal uses a `.patient-theme` wrapper to switch to a blue/gold
// palette while every other dashboard keeps the default teal `:root` values.
// Channel form (`R G B`) is required so Tailwind's `/opacity` modifiers still
// compile to `rgb(... / <alpha>)`.
const c = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": c("on-tertiary-fixed-variant"),
        "on-error-container": c("on-error-container"),
        "surface-container-low": c("surface-container-low"),
        "secondary-fixed-dim": c("secondary-fixed-dim"),
        "on-secondary-container": c("on-secondary-container"),
        "secondary-fixed": c("secondary-fixed"),
        "secondary-container": c("secondary-container"),
        "tertiary": c("tertiary"),
        "primary-fixed-dim": c("primary-fixed-dim"),
        "on-tertiary-container": c("on-tertiary-container"),
        "on-primary-fixed": c("on-primary-fixed"),
        "on-surface": c("on-surface"),
        "surface-variant": c("surface-variant"),
        "surface": c("surface"),
        "tertiary-fixed-dim": c("tertiary-fixed-dim"),
        "inverse-on-surface": c("inverse-on-surface"),
        "inverse-surface": c("inverse-surface"),
        "outline": c("outline"),
        "on-surface-variant": c("on-surface-variant"),
        "on-error": c("on-error"),
        "tertiary-container": c("tertiary-container"),
        "on-secondary-fixed-variant": c("on-secondary-fixed-variant"),
        "on-secondary": c("on-secondary"),
        "on-background": c("on-background"),
        "surface-container": c("surface-container"),
        "surface-container-lowest": c("surface-container-lowest"),
        "on-primary-container": c("on-primary-container"),
        "inverse-primary": c("inverse-primary"),
        "surface-bright": c("surface-bright"),
        "primary": c("primary"),
        "on-primary-fixed-variant": c("on-primary-fixed-variant"),
        "on-secondary-fixed": c("on-secondary-fixed"),
        "surface-container-high": c("surface-container-high"),
        "error": c("error"),
        "secondary": c("secondary"),
        "surface-dim": c("surface-dim"),
        "outline-variant": c("outline-variant"),
        "on-tertiary-fixed": c("on-tertiary-fixed"),
        "on-primary": c("on-primary"),
        "surface-container-highest": c("surface-container-highest"),
        "primary-container": c("primary-container"),
        "on-tertiary": c("on-tertiary"),
        "tertiary-fixed": c("tertiary-fixed"),
        "primary-fixed": c("primary-fixed"),
        "background": c("background"),
        "error-container": c("error-container"),
        "surface-tint": c("surface-tint"),
        ok: c("ok"),
        warn: c("warn"),
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", "3xl": "1.5rem", full: "9999px" },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        base: "8px",
        unit: "4px",
        "container-max": "1280px",
        gutter: "24px",
        "grid-gutter": "16px",
        "grid-margin": "24px",
        lg: "24px",
        md: "16px",
        sm: "8px",
        xs: "4px",
        xl: "32px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-xs": "4px",
        "stack-xl": "40px",
      },
      maxWidth: { "container-max": "1280px" },
      fontFamily: {
        // Headline/display families read a CSS var so the patient theme can swap
        // to Plus Jakarta Sans without changing body/label text.
        "headline-xl": ["var(--font-headline)", "sans-serif"],
        "headline-md": ["var(--font-headline)", "sans-serif"],
        "headline-lg": ["var(--font-headline)", "sans-serif"],
        "display-lg": ["var(--font-headline)", "sans-serif"],
        "title-lg": ["var(--font-headline)", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
