/** @type {import('tailwindcss').Config} */
// Design tokens pulled from the Stitch "NUHRS Health Portal" project.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f8f9fa",
        surface: "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeef",
        "surface-container-highest": "#e1e3e4",
        primary: "#007DCC",
        "primary-container": "#007DCC",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-surface-variant": "#404751",
        outline: "#707882",
        "outline-variant": "#c0c7d3",
        secondary: "#D10056",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        ok: "#1f7a34",
        warn: "#b26a00",
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        base: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-xs": "4px",
        "stack-xl": "40px",
      },
      maxWidth: { "container-max": "1280px" },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
