/** @type {import('tailwindcss').Config} */
// Design tokens pulled from the Stitch "NUHRS Health Portal" project.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#6f380b",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f5",
        "secondary-fixed-dim": "#a1c9ff",
        "on-secondary-container": "#004377",
        "secondary-fixed": "#d2e4ff",
        "secondary-container": "#6fb1ff",
        "tertiary": "#85481b",
        "primary-fixed-dim": "#7cd4df",
        "on-tertiary-container": "#fff3ee",
        "on-primary-fixed": "#001f23",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "surface": "#f8fafb",
        "tertiary-fixed-dim": "#ffb688",
        "inverse-on-surface": "#eff1f2",
        "inverse-surface": "#2e3132",
        "outline": "#6e797a",
        "on-surface-variant": "#3e494a",
        "on-error": "#ffffff",
        "tertiary-container": "#a26031",
        "on-secondary-fixed-variant": "#00487f",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "surface-container": "#eceeef",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ddfbff",
        "inverse-primary": "#7cd4df",
        "surface-bright": "#f8fafb",
        "primary": "#00626a",
        "on-primary-fixed-variant": "#004f56",
        "on-secondary-fixed": "#001c37",
        "surface-container-high": "#e6e8e9",
        "error": "#ba1a1a",
        "secondary": "#0061a7",
        "surface-dim": "#d8dadb",
        "outline-variant": "#bdc9ca",
        "on-tertiary-fixed": "#311300",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#0e7c86",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbc7",
        "primary-fixed": "#98f0fb",
        "background": "#f8fafb",
        "error-container": "#ffdad6",
        "surface-tint": "#006972",
        ok: "#1f7a34",
        warn: "#b26a00",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        base: "8px",
        unit: "4px",
        "container-max": "1280px",
        gutter: "24px",
        "grid-gutter": "16px",
        "grid-margin": "24px",
        lg: "24px",
        md: "16px",
        sm: "8px",
        xs: "4px",
        xl: "32px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-xs": "4px",
        "stack-xl": "40px",
      },
      maxWidth: { "container-max": "1280px" },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
